### ISSUE TITLE
After I run python extract_slices.py, the resulting mydata_full_data_with_slices.json file contains only [ ]

### ISSUE THREAD

**Issue by Fangweijun111** [VulScribeR/VulScribeR#2]
Thank you very much for your earlier reply. When I run steps 3 and 4 of VulScribeR/models/Devign and Reveal /readme.md, extract_slices. py error prompt lack clang.cindex, clang.enumerations, numpy and graphviz, so I installed these packages and run python extract_slices.py. After generating mydata_full_data_with_slices.json, it has only [ ]. So I want to know the versions of your dependencies, especially the ones above. I guess it's because of the different versions. Here are my environmental dependencies.
![QQ_1725873757480](https://github.com/user-attachments/assets/127b6a64-7ba2-43ea-82f9-efab2c494a88)

**Comment by VulScribeR** [comment]
Thanks for making me realize that I forgot to put in the requirements.txt files.
You can create the [Devign](https://github.com/VulScribeR/VulScribeR/blob/main/requirements-devign-env.txt) and [Reveal](https://github.com/VulScribeR/VulScribeR/blob/main/requirements-reveal-env.txt) environments using the requirement files added at the project's root.

**Comment by VulScribeR** [comment]
The following files were updated with requirements information for Reveal, Devign, and the default environments:
- https://github.com/VulScribeR/VulScribeR/blob/main/code/readme.md
- https://github.com/VulScribeR/VulScribeR/blob/main/models/Devign%20and%20Reveal/readme.md#notes
- https://github.com/VulScribeR/VulScribeR/blob/main/models/Linevul/readme.md
