### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './raw_code_deb_chro.100.wv.vectors.npy'

### ISSUE THREAD

**Issue by Fangweijun111** [VulScribeR/VulScribeR#3]
When I run `bash get_ggnn_input.sh `, it reports `FileNotFoundError: [Errno 2] No such file or directory: './raw_code_deb_chro.100.wv.vectors.npy' `. My guess is that  .npy file is required internally for the load method called on line 391 of create ggnn data.py. I was wondering if you have this file. If so, I would be most grateful. I also tried to manually extract the target file from the.wv file, but without success.

**Comment by VulScribeR** [comment]
Thanks for bringing this to my attention. That file was discarded during the commit for being bigger than GitHub's limit.

I have added two neglected files, including the [`'./raw_code_deb_chro.100.wv.vectors.npy'`](https://github.com/VulScribeR/VulScribeR/releases/download/Release/raw_code_deb_chro.100.wv.vectors.npy) to the [release](https://github.com/VulScribeR/VulScribeR/releases/tag/Release). Let me know if it fixes the problem. Thanks!

**Comment by VulScribeR** [comment]
Updated https://github.com/VulScribeR/VulScribeR/blob/main/models/Devign%20and%20Reveal/readme.md

**Comment by Fangweijun111** [comment]
Thank you very much. The problem has been fixed, but before I run sh reveal_embed.py, I need to manually create a folder called demo under the models/Devign and Reveal paths. Then move in the mydata.json.shard* generated in the previous step. And change the input file name in the following code for the reveal_embed.py file                  
```
    else:
        dataset = DataSet(train_src=['mydata.json.shard1', 'mydata.json.shard2'], 
                        valid_src=['mydata.json.shard3'],
                        test_src=['mydata.json.shard4'],
                        batch_size=args.batch_size, n_ident=args.node_tag, g_ident=args.graph_tag,
                        l_ident=args.label_tag)
```

**Comment by VulScribeR** [comment]
You can run Devign first and create a demo folder. Devign prepares the data and puts it in the demo directory. Then you can run reveal_embed.py. (This is what I used to do)

But if you are asking how train/test/validation should be selected, I refer you to the devign_demo.py file (the same may be applied to reveal_embed.py):

`        dataset = DataSet(train_src=['train.json.shard1','train.json.shard2','train.json.shard3','train.json.shard4','train.json.shard5', 'train.json.shard6', 'train.json.shard7', 'train.json.shard8','train.json.shard9','train.json.shard10'],
                          valid_src=None,
                          test_src=['bigvul.json.shard1', 'bigvul.json.shard2', 'bigvul.json.shard3'],
                          batch_size=args.batch_size, n_ident=args.node_tag, g_ident=args.graph_tag,
                          l_ident=args.label_tag)`

Note that we followed previous studies and did not use a validation set for selecting the best checkpoint and instead trained 5 times and selected the best-performing model. So, valid_src can be None and it will run without facing any errors. 
Does this answer your question?

**Comment by Fangweijun111** [comment]
Thank you very much, I have now successfully reproduced the REVEAL model, my last problem was because I had not reproduced the Devign model, so I thought there was a slight problem with the README.md file step. This is the first time I have reproduced the model, thanks again for your many replies, I will try to reproduce your other experiments again, good luck with your academic career!

**Comment by VulScribeR** [comment]
Thanks for all your comments and the constructive issues you created. 
Good luck to you too!
